subroutine internal_lidort(TS_DO_FULLRAD_MODE, TS_DO_THERMAL_EMISSION, TS_DO_SURFACE_EMISSION, TS_DO_PLANE_PARALLEL, &
                  TS_DO_BRDF_SURFACE, TS_DO_UPWELLING, TS_DO_DNWELLING, TS_DO_TOA_CONTRIBS, TS_DO_SURFACE_LEAVING, &
                  TS_DO_SL_ISOTROPIC, TS_DO_WATER_LEAVING, TS_DO_FLUORESCENCE, TS_DO_TF_ITERATION, &
                  TS_DO_WLADJUSTED_OUTPUT, TS_DO_TOA_ILLUMINATION, TS_DO_BOA_ILLUMINATION, TS_DO_ALBTRN_MEDIA, &
                  TS_DO_PLANETARY_PROBLEM, TS_DO_MSSTS, &
                  TS_TAYLOR_ORDER, TS_NSTREAMS, TS_NLAYERS, TS_NFINELAYERS, TS_N_THERMAL_COEFFS, TS_LIDORT_ACCURACY, &
                  TS_ASYMTX_TOLERANCE, TS_TF_MAXITER, TS_TF_CRITERION, TS_TOA_ILLUMINATION, TS_BOA_ILLUMINATION, TS_FLUX_FACTOR, &
                  TS_HEIGHT_GRID, TS_PRESSURE_GRID, TS_TEMPERATURE_GRID, TS_FINEGRID, TS_RFINDEX_PARAMETER, &
                  TS_DELTAU_VERT_INPUT, TS_PHASMOMS_TOTAL_INPUT, TS_PHASFUNC_INPUT_UP, TS_PHASFUNC_INPUT_DN, TS_LAMBERTIAN_ALBEDO, &
                  TS_THERMAL_BB_INPUT, TS_SURFACE_BB_INPUT, TS_ATMOS_WAVELENGTH, &
                  TS_DO_DEBUG_WRITE, TS_DO_WRITE_INPUT, TS_INPUT_WRITE_FILENAME, TS_DO_WRITE_SCENARIO, TS_SCENARIO_WRITE_FILENAME, &
                  TS_DO_WRITE_FOURIER, TS_FOURIER_WRITE_FILENAME, TS_DO_WRITE_RESULTS, TS_RESULTS_WRITE_FILENAME, &
                  TS_DO_FOCORR, TS_DO_FOCORR_EXTERNAL, TS_DO_FOCORR_NADIR, TS_DO_FOCORR_OUTGOING, TS_DO_SSCORR_TRUNCATION, &
                  TS_DO_SSCORR_USEPHASFUNC, &
                  TS_DO_EXTERNAL_WLEAVE, TS_DO_DOUBLE_CONVTEST, TS_DO_SOLAR_SOURCES, TS_DO_REFRACTIVE_GEOMETRY, &
                  TS_DO_CHAPMAN_FUNCTION, TS_N_USER_LEVELS, &
                  TS_DO_RAYLEIGH_ONLY, &
                  TS_DO_ISOTROPIC_ONLY, TS_DO_NO_AZIMUTH, TS_DO_ALL_FOURIER, TS_DO_DELTAM_SCALING, TS_DO_SOLUTION_SAVING, &
                  TS_DO_BVP_TELESCOPING, &
                  TS_DO_USER_STREAMS, TS_DO_ADDITIONAL_MVOUT, TS_DO_MVOUT_ONLY, TS_DO_THERMAL_TRANSONLY, &
                  TS_DO_OBSERVATION_GEOMETRY, &
                  TS_DO_DOUBLET_GEOMETRY, &
                  TS_NMOMENTS_INPUT, TS_NBEAMS, TS_BEAM_SZAS, TS_N_USER_RELAZMS, TS_USER_RELAZMS, &
                  TS_N_USER_STREAMS, TS_USER_ANGLES_INPUT, &
                  TS_USER_LEVELS, TS_GEOMETRY_SPECHEIGHT, TS_N_USER_OBSGEOMS, TS_USER_OBSGEOMS_INPUT, &
                  TS_N_USER_DOUBLETS, TS_USER_DOUBLETS, &
                  TS_EARTH_RADIUS, TS_OMEGA_TOTAL_INPUT, TS_N_SURFACE_WFS, &
                  TS_LAYER_VARY_FLAG, TS_LAYER_VARY_NUMBER, TS_N_TOTALCOLUMN_WFS, TS_N_SLEAVE_WFS, &
                  TS_COLUMNWF_NAMES, TS_PROFILEWF_NAMES, TS_L_DELTAU_VERT_INPUT, TS_L_OMEGA_TOTAL_INPUT, &
                  TS_L_PHASMOMS_TOTAL_INPUT, TS_L_PHASFUNC_INPUT_UP, TS_L_PHASFUNC_INPUT_DN, &
                  TS_DO_COLUMN_LINEARIZATION, TS_DO_PROFILE_LINEARIZATION, TS_DO_ATMOS_LINEARIZATION, &
                  TS_DO_SURFACE_LINEARIZATION, TS_DO_LINEARIZATION, TS_DO_SIMULATION_ONLY, TS_DO_ATMOS_LBBF, &
                  TS_DO_SURFACE_LBBF, TS_DO_SLEAVE_WFS, NUM_REPEAT, &
                  TS_INTENSITY, TS_MEANI_DIFFUSE, TS_FLUX_DIFFUSE, TS_DNMEANI_DIRECT, TS_DNFLUX_DIRECT, &
                  TS_ALBMED_USER, TS_TRNMED_USER, TS_ALBMED_FLUXES, TS_TRNMED_FLUXES, TS_PLANETARY_TRANSTERM, &
                  TS_PLANETARY_SBTERM, TS_PATHGEOMS, TS_LOSTRANS, TS_LAYER_MSSTS, TS_SURF_MSSTS, &
                  TS_CONTRIBS, TS_COLUMNWF, TS_MEANI_DIFFUSE_COLWF, TS_FLUX_DIFFUSE_COLWF, TS_DNMEANI_DIRECT_COLWF, &
                  TS_DNFLUX_DIRECT_COLWF, &
                  TS_PROFILEWF, TS_MEANI_DIFFUSE_PROFWF, TS_FLUX_DIFFUSE_PROFWF, TS_DNMEANI_DIRECT_PROFWF, &
                  TS_DNFLUX_DIRECT_PROFWF, &
                  TS_ABBWFS_JACOBIANS, TS_ABBWFS_FLUXES, TS_ALBMED_USER_PROFWF, TS_TRNMED_USER_PROFWF, &
                  TS_ALBMED_FLUXES_PROFWF, &
                  TS_TRNMED_FLUXES_PROFWF, TS_TRANSBEAM_PROFWF, TS_ALBMED_USER_COLWF, TS_TRNMED_USER_COLWF, &
                  TS_ALBMED_FLUXES_COLWF, &
                  TS_TRNMED_FLUXES_COLWF, TS_TRANSBEAM_COLWF, TS_PLANETARY_TRANSTERM_PROFWF, TS_PLANETARY_SBTERM_PROFWF, &
                  TS_PLANETARY_TRANSTERM_COLWF, TS_PLANETARY_SBTERM_COLWF, &
                  TS_LC_LOSTRANS, &
                  TS_LC_LAYER_MSSTS, TS_LC_SURF_MSSTS, TS_LP_LOSTRANS, TS_LP_LAYER_MSSTS, TS_LP_SURF_MSSTS, &
                  TS_SURFACEWF, &
                  TS_MEANI_DIFFUSE_SURFWF, TS_FLUX_DIFFUSE_SURFWF, TS_SBBWFS_JACOBIANS, TS_SBBWFS_FLUXES, TS_LS_LAYER_MSSTS, &
                  TS_LS_SURF_MSSTS)
   USE LIDORT_pars_m
   USE LIDORT_IO_DEFS_m
   USE LIDORT_LIN_IO_DEFS_m

   USE LIDORT_AUX_m,    Only : LIDORT_WRITE_STATUS
   USE LIDORT_MASTERS_m
   USE LIDORT_LPS_masters_m

   implicit none

   INTEGER, parameter :: WRAP_MAXLAYERS = 200
   INTEGER, parameter :: WRAP_MAXMOMENTS_INPUT = 200
   INTEGER, parameter :: WRAP_MAX_GEOMETRIES = 8
   INTEGER, parameter :: WRAP_MAXBEAMS = 8
   INTEGER, parameter :: WRAP_MAX_USER_RELAZMS = 1
   INTEGER, parameter :: WRAP_MAX_USER_STREAMS = 1
   INTEGER, parameter :: WRAP_MAX_USER_LEVELS = 2
   INTEGER, parameter :: WRAP_MAX_USER_OBSGEOMS = 8
   INTEGER, parameter :: WRAP_MAX_ATMOSWFS = 3
   INTEGER, parameter :: WRAP_MAX_DIRECTIONS = 2
   INTEGER, parameter :: WRAP_MAX_SURFACEWFS = 1

   LOGICAL, parameter :: do_debug_input = .false.

   logical         :: OPENFILEFLAG
   integer         :: m, n, v, l


!  LIDORT input structures

   TYPE(LIDORT_Fixed_Inputs)             :: LIDORT_FixIn
   TYPE(LIDORT_Modified_Inputs)          :: LIDORT_ModIn

   TYPE(LIDORT_Fixed_LinInputs)          :: LIDORT_LinFixIn
   TYPE(LIDORT_Modified_LinInputs)       :: LIDORT_LinModIn

!  LIDORT supplements i/o structure

   TYPE(LIDORT_Sup_InOut)                :: LIDORT_Sup
   TYPE(LIDORT_LinSup_InOut)             :: LIDORT_LinSup

!  LIDORT output structure

   TYPE(LIDORT_Outputs)                  :: LIDORT_Out
   TYPE(LIDORT_LinOutputs)               :: LIDORT_LinOut


! Input Fixed Boolean

   LOGICAL     :: TS_DO_FULLRAD_MODE
   LOGICAL     :: TS_DO_THERMAL_EMISSION
   LOGICAL     :: TS_DO_SURFACE_EMISSION
   LOGICAL     :: TS_DO_PLANE_PARALLEL
   LOGICAL     :: TS_DO_BRDF_SURFACE
   LOGICAL     :: TS_DO_UPWELLING
   LOGICAL     :: TS_DO_DNWELLING
   LOGICAL     :: TS_DO_TOA_CONTRIBS
   LOGICAL     :: TS_DO_SURFACE_LEAVING
   LOGICAL     :: TS_DO_SL_ISOTROPIC
   LOGICAL     :: TS_DO_WATER_LEAVING
   LOGICAL     :: TS_DO_FLUORESCENCE
   LOGICAL     :: TS_DO_TF_ITERATION
   LOGICAL     :: TS_DO_WLADJUSTED_OUTPUT
   LOGICAL     :: TS_DO_TOA_ILLUMINATION
   LOGICAL     :: TS_DO_BOA_ILLUMINATION
   LOGICAL     :: TS_DO_ALBTRN_MEDIA(2)
   LOGICAL     :: TS_DO_PLANETARY_PROBLEM
   LOGICAL     :: TS_DO_MSSTS

! Input Fixed Control

   INTEGER   :: TS_TAYLOR_ORDER
   INTEGER   :: TS_NSTREAMS
   INTEGER   :: TS_NLAYERS
   INTEGER   :: TS_NFINELAYERS
   INTEGER   :: TS_N_THERMAL_COEFFS
   REAL(8) :: TS_LIDORT_ACCURACY
   REAL(8) :: TS_ASYMTX_TOLERANCE
   INTEGER   :: TS_TF_MAXITER
   REAL(8) :: TS_TF_CRITERION
   REAL(8) :: TS_TOA_ILLUMINATION
   REAL(8) :: TS_BOA_ILLUMINATION

! Input Fixed Sunrays

   REAL(8)  :: TS_FLUX_FACTOR

! Input Fixed Chapman
   REAL(8), dimension (0:WRAP_MAXLAYERS), intent(inout) :: TS_HEIGHT_GRID
   REAL(8), dimension (0:WRAP_MAXLAYERS), intent(inout) :: TS_PRESSURE_GRID
   REAL(8), dimension (0:WRAP_MAXLAYERS), intent(inout) :: TS_TEMPERATURE_GRID
   INTEGER,   dimension (WRAP_MAXLAYERS), intent(inout)   :: TS_FINEGRID
   REAL(8) :: TS_RFINDEX_PARAMETER

! Input fixed Optical

   REAL(8), dimension ( WRAP_MAXLAYERS ), intent(inout) :: TS_DELTAU_VERT_INPUT
   REAL(8), dimension ( 0:WRAP_MAXMOMENTS_INPUT, WRAP_MAXLAYERS ), intent(inout) :: TS_PHASMOMS_TOTAL_INPUT
   REAL(8), dimension ( WRAP_MAXLAYERS, WRAP_MAX_GEOMETRIES ), intent(inout) :: TS_PHASFUNC_INPUT_UP
   REAL(8), dimension ( WRAP_MAXLAYERS, WRAP_MAX_GEOMETRIES ), intent(inout) :: TS_PHASFUNC_INPUT_DN
   REAL(8) :: TS_LAMBERTIAN_ALBEDO
   REAL(8), dimension ( 0:WRAP_MAXLAYERS ), intent(inout) :: TS_THERMAL_BB_INPUT
   REAL(8) :: TS_SURFACE_BB_INPUT
   REAL(8) :: TS_ATMOS_WAVELENGTH

! Input fixed User

   INTEGER  :: TS_N_USER_LEVELS

! Input fixed Write
   LOGICAL ::            TS_DO_DEBUG_WRITE
   LOGICAL ::            TS_DO_WRITE_INPUT
   CHARACTER (LEN=60) :: TS_INPUT_WRITE_FILENAME
   LOGICAL ::            TS_DO_WRITE_SCENARIO
   CHARACTER (LEN=60) :: TS_SCENARIO_WRITE_FILENAME
   LOGICAL ::            TS_DO_WRITE_FOURIER
   CHARACTER (LEN=60) :: TS_FOURIER_WRITE_FILENAME
   LOGICAL ::            TS_DO_WRITE_RESULTS
   CHARACTER (LEN=60) :: TS_RESULTS_WRITE_FILENAME

! Input Modified Bool
   LOGICAL    :: TS_DO_FOCORR
   LOGICAL    :: TS_DO_FOCORR_EXTERNAL
   LOGICAL    :: TS_DO_FOCORR_NADIR
   LOGICAL    :: TS_DO_FOCORR_OUTGOING
   LOGICAL    :: TS_DO_SSCORR_TRUNCATION
   LOGICAL    :: TS_DO_SSCORR_USEPHASFUNC
   LOGICAL    :: TS_DO_EXTERNAL_WLEAVE
   LOGICAL    :: TS_DO_DOUBLE_CONVTEST
   LOGICAL    :: TS_DO_SOLAR_SOURCES
   LOGICAL    :: TS_DO_REFRACTIVE_GEOMETRY
   LOGICAL    :: TS_DO_CHAPMAN_FUNCTION
   LOGICAL    :: TS_DO_RAYLEIGH_ONLY
   LOGICAL    :: TS_DO_ISOTROPIC_ONLY
   LOGICAL    :: TS_DO_NO_AZIMUTH
   LOGICAL    :: TS_DO_ALL_FOURIER
   LOGICAL    :: TS_DO_DELTAM_SCALING
   LOGICAL    :: TS_DO_SOLUTION_SAVING
   LOGICAL    :: TS_DO_BVP_TELESCOPING
   LOGICAL    :: TS_DO_USER_STREAMS
   LOGICAL    :: TS_DO_ADDITIONAL_MVOUT
   LOGICAL    :: TS_DO_MVOUT_ONLY
   LOGICAL    :: TS_DO_THERMAL_TRANSONLY
   LOGICAL    :: TS_DO_OBSERVATION_GEOMETRY
   LOGICAL    :: TS_DO_DOUBLET_GEOMETRY

! Input Modified Control

   INTEGER   :: TS_NMOMENTS_INPUT

! Input Modified Sunrays

   INTEGER    :: TS_NBEAMS
   REAL(8), dimension (WRAP_MAXBEAMS), intent(inout) :: TS_BEAM_SZAS

! Input Modified User Values

   INTEGER                                 :: TS_N_USER_RELAZMS
   REAL(8), dimension (WRAP_MAX_USER_RELAZMS), intent(inout) :: TS_USER_RELAZMS
   INTEGER                                 :: TS_N_USER_STREAMS
   REAL(8), dimension (WRAP_MAX_USER_STREAMS), intent(inout) :: TS_USER_ANGLES_INPUT
   REAL(8), dimension (WRAP_MAX_USER_LEVELS), intent(inout)  :: TS_USER_LEVELS
   REAL(8)                               :: TS_GEOMETRY_SPECHEIGHT
   INTEGER                                 :: TS_N_USER_OBSGEOMS
   REAL(8), dimension (WRAP_MAX_USER_OBSGEOMS,3), intent(inout) :: TS_USER_OBSGEOMS_INPUT
   INTEGER                                   :: TS_N_USER_DOUBLETS
   REAL(8), dimension (WRAP_MAX_USER_STREAMS,2), intent(inout) :: TS_USER_DOUBLETS


! Input Modified Chapman

   REAL(8) :: TS_EARTH_RADIUS

! Input Modified Optical

   REAL(8), dimension ( WRAP_MAXLAYERS ), intent(inout) :: TS_OMEGA_TOTAL_INPUT

! Input Fixed Lin Control

   LOGICAL, dimension(WRAP_MAXLAYERS), intent(in)  :: TS_LAYER_VARY_FLAG
   INTEGER, dimension(WRAP_MAXLAYERS), intent(inout)  :: TS_LAYER_VARY_NUMBER
   INTEGER  :: TS_N_TOTALCOLUMN_WFS
   INTEGER  :: TS_N_SURFACE_WFS
   INTEGER  :: TS_N_SLEAVE_WFS
   CHARACTER (LEN=31), dimension(WRAP_MAX_ATMOSWFS), intent(in) :: TS_COLUMNWF_NAMES
   CHARACTER (LEN=31), dimension(WRAP_MAX_ATMOSWFS), intent(in) :: TS_PROFILEWF_NAMES

! Input Lin Fixed Optical

   REAL(8), dimension(WRAP_MAX_ATMOSWFS,WRAP_MAXLAYERS), intent(inout) :: TS_L_DELTAU_VERT_INPUT
   REAL(8), dimension(WRAP_MAX_ATMOSWFS,WRAP_MAXLAYERS), intent(inout) :: TS_L_OMEGA_TOTAL_INPUT
   REAL(8), dimension(WRAP_MAX_ATMOSWFS,0:WRAP_MAXMOMENTS_INPUT,WRAP_MAXLAYERS), intent(inout) :: TS_L_PHASMOMS_TOTAL_INPUT
   REAL(8), intent(inout) :: TS_L_PHASFUNC_INPUT_UP ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_GEOMETRIES )
   REAL(8), intent(inout) :: TS_L_PHASFUNC_INPUT_DN ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_GEOMETRIES )

! Input Lin Modified Control

   LOGICAL  :: TS_DO_COLUMN_LINEARIZATION
   LOGICAL  :: TS_DO_PROFILE_LINEARIZATION
   LOGICAL  :: TS_DO_ATMOS_LINEARIZATION
   LOGICAL  :: TS_DO_SURFACE_LINEARIZATION
   LOGICAL  :: TS_DO_LINEARIZATION
   LOGICAL  :: TS_DO_SIMULATION_ONLY
   LOGICAL  :: TS_DO_ATMOS_LBBF
   LOGICAL  :: TS_DO_SURFACE_LBBF
   LOGICAL  :: TS_DO_SLEAVE_WFS

! Input ADDED FOR DEBUG

   ! Number of times to repeat the caluclation, used to test performance overhead
   INTEGER :: NUM_REPEAT

! Output Main

   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAX_GEOMETRIES, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_INTENSITY
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_MEANI_DIFFUSE
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_FLUX_DIFFUSE
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNMEANI_DIRECT
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNFLUX_DIRECT
   REAL(8), dimension ( WRAP_MAX_USER_STREAMS ), intent(inout) :: TS_ALBMED_USER, TS_TRNMED_USER
   REAL(8), intent(inout)                                 :: TS_ALBMED_FLUXES(2), TS_TRNMED_FLUXES(2)
   REAL(8), dimension (  WRAP_MAX_GEOMETRIES ), intent(inout) :: TS_PLANETARY_TRANSTERM
   REAL(8), intent(inout)                                :: TS_PLANETARY_SBTERM
   REAL(8), DIMENSION ( 2, 0:WRAP_MAXLAYERS ), intent(inout)      :: TS_PATHGEOMS
   REAL(8), DIMENSION ( WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LOSTRANS
   REAL(8), DIMENSION ( WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LAYER_MSSTS
   REAL(8), DIMENSION ( WRAP_MAXBEAMS ), intent(inout)            :: TS_SURF_MSSTS
   REAL(8), DIMENSION ( WRAP_MAX_GEOMETRIES, WRAP_MAXLAYERS ), intent(inout) :: TS_CONTRIBS

! Output Lin Atmos

   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAX_USER_LEVELS, WRAP_MAX_GEOMETRIES, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_COLUMNWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_MEANI_DIFFUSE_COLWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_FLUX_DIFFUSE_COLWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNMEANI_DIRECT_COLWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNFLUX_DIRECT_COLWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_USER_LEVELS, WRAP_MAX_GEOMETRIES, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_PROFILEWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_MEANI_DIFFUSE_PROFWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_FLUX_DIFFUSE_PROFWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNMEANI_DIRECT_PROFWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS ), intent(inout) :: TS_DNFLUX_DIRECT_PROFWF
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAX_USER_STREAMS, 0:WRAP_MAXLAYERS, WRAP_MAX_DIRECTIONS), intent(inout) :: TS_ABBWFS_JACOBIANS
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, 2, 0:WRAP_MAXLAYERS, WRAP_MAX_DIRECTIONS), intent(inout)                :: TS_ABBWFS_FLUXES
   REAL(8), dimension ( WRAP_MAX_USER_STREAMS, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_ALBMED_USER_PROFWF
   REAL(8), dimension ( WRAP_MAX_USER_STREAMS, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_TRNMED_USER_PROFWF
   REAL(8), dimension ( 2, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout)                :: TS_ALBMED_FLUXES_PROFWF
   REAL(8), dimension ( 2, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout)                :: TS_TRNMED_FLUXES_PROFWF
   REAL(8), dimension ( WRAP_MAXBEAMS, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout)         :: TS_TRANSBEAM_PROFWF
   REAL(8), dimension ( WRAP_MAX_USER_STREAMS, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_ALBMED_USER_COLWF
   REAL(8), dimension ( WRAP_MAX_USER_STREAMS, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_TRNMED_USER_COLWF
   REAL(8), dimension ( 2, WRAP_MAX_ATMOSWFS ), intent(inout)                :: TS_ALBMED_FLUXES_COLWF
   REAL(8), dimension ( 2, WRAP_MAX_ATMOSWFS ), intent(inout)                :: TS_TRNMED_FLUXES_COLWF
   REAL(8), dimension ( WRAP_MAXBEAMS, WRAP_MAX_ATMOSWFS ), intent(inout)         :: TS_TRANSBEAM_COLWF
   REAL(8), dimension ( WRAP_MAX_GEOMETRIES, WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_PLANETARY_TRANSTERM_PROFWF
   REAL(8), dimension ( WRAP_MAXLAYERS, WRAP_MAX_ATMOSWFS ), intent(inout)                 :: TS_PLANETARY_SBTERM_PROFWF
   REAL(8), dimension ( WRAP_MAX_GEOMETRIES, WRAP_MAX_ATMOSWFS ), intent(inout) :: TS_PLANETARY_TRANSTERM_COLWF
   REAL(8), dimension ( WRAP_MAX_ATMOSWFS ), intent(inout)                 :: TS_PLANETARY_SBTERM_COLWF
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LC_LOSTRANS
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LC_LAYER_MSSTS
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXBEAMS ), intent(inout)            :: TS_LC_SURF_MSSTS
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout)            :: TS_LP_LOSTRANS
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LP_LAYER_MSSTS
   REAL(8), DIMENSION ( WRAP_MAX_ATMOSWFS, WRAP_MAXLAYERS, WRAP_MAXBEAMS ), intent(inout)            :: TS_LP_SURF_MSSTS

! Output Lin Surf

   REAL(8), dimension ( WRAP_MAX_SURFACEWFS, WRAP_MAX_USER_LEVELS, WRAP_MAX_GEOMETRIES, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_SURFACEWF
   REAL(8), dimension ( WRAP_MAX_SURFACEWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_MEANI_DIFFUSE_SURFWF
   REAL(8), dimension ( WRAP_MAX_SURFACEWFS, WRAP_MAX_USER_LEVELS, WRAP_MAXBEAMS, WRAP_MAX_DIRECTIONS ), intent(inout) :: TS_FLUX_DIFFUSE_SURFWF
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, WRAP_MAX_USER_STREAMS, WRAP_MAX_DIRECTIONS), intent(inout) :: TS_SBBWFS_JACOBIANS
   REAL(8), dimension ( WRAP_MAX_USER_LEVELS, 2, WRAP_MAX_DIRECTIONS), intent(inout)                :: TS_SBBWFS_FLUXES
   REAL(8), DIMENSION ( WRAP_MAX_SURFACEWFS, WRAP_MAXBEAMS, WRAP_MAXLAYERS ), intent(inout) :: TS_LS_LAYER_MSSTS
   REAL(8), DIMENSION ( WRAP_MAX_SURFACEWFS, WRAP_MAXBEAMS ), intent(inout)            :: TS_LS_SURF_MSSTS


!  bookkeeping
!  -----------

!  Fourier numbers used (bookkeeping)

      INTEGER, dimension ( MAXBEAMS )  :: TS_FOURIER_SAVED

!  Number of geometries (bookkeeping output)

      INTEGER                          :: TS_N_GEOMETRIES

!  Solar Beam Transmittance to BOA
!  rob fix 11/27/2014, for diagnostic use only

      REAL(8), dimension ( MAXBEAMS ) :: TS_SOLARBEAM_BOATRANS

!  4/22/19. for Version 3.8.1. Spherical Albedo and Transmittances
!  ---------------------------------------------------------------

!   Required for the planetary problem

      real(8) :: TS_SPHERALB
      real(8) :: TS_TRANS1_USER ( MAX_USER_STREAMS)
      real(8) :: TS_TRANS1_BEAM ( MAXBEAMS)

! Copy to LIDORT Structures

   LIDORT_FixIn%Bool%TS_DO_FULLRAD_MODE = TS_DO_FULLRAD_MODE
   LIDORT_FixIn%Bool%TS_DO_THERMAL_EMISSION = TS_DO_THERMAL_EMISSION
   LIDORT_FixIn%Bool%TS_DO_SURFACE_EMISSION = TS_DO_SURFACE_EMISSION
   LIDORT_FixIn%Bool%TS_DO_PLANE_PARALLEL = TS_DO_PLANE_PARALLEL
   LIDORT_FixIn%Bool%TS_DO_BRDF_SURFACE = TS_DO_BRDF_SURFACE
   LIDORT_FixIn%Bool%TS_DO_UPWELLING = TS_DO_UPWELLING
   LIDORT_FixIn%Bool%TS_DO_DNWELLING = TS_DO_DNWELLING
   LIDORT_FixIn%Bool%TS_DO_TOA_CONTRIBS = TS_DO_TOA_CONTRIBS
   LIDORT_FixIn%Bool%TS_DO_SURFACE_LEAVING = TS_DO_SURFACE_LEAVING
   LIDORT_FixIn%Bool%TS_DO_SL_ISOTROPIC = TS_DO_SL_ISOTROPIC
   LIDORT_FixIn%Bool%TS_DO_WATER_LEAVING = TS_DO_WATER_LEAVING
   LIDORT_FixIn%Bool%TS_DO_FLUORESCENCE = TS_DO_FLUORESCENCE
   LIDORT_FixIn%Bool%TS_DO_TF_ITERATION = TS_DO_TF_ITERATION
   LIDORT_FixIn%Bool%TS_DO_WLADJUSTED_OUTPUT = TS_DO_WLADJUSTED_OUTPUT
   LIDORT_FixIn%Bool%TS_DO_TOA_ILLUMINATION = TS_DO_TOA_ILLUMINATION
   LIDORT_FixIn%Bool%TS_DO_BOA_ILLUMINATION = TS_DO_BOA_ILLUMINATION
   LIDORT_FixIn%Bool%TS_DO_ALBTRN_MEDIA = TS_DO_ALBTRN_MEDIA
   LIDORT_FixIn%Bool%TS_DO_PLANETARY_PROBLEM = TS_DO_PLANETARY_PROBLEM
   LIDORT_FixIn%Bool%TS_DO_MSSTS = TS_DO_MSSTS

   LIDORT_FixIn%Cont%TS_TAYLOR_ORDER = TS_TAYLOR_ORDER
   LIDORT_FixIn%Cont%TS_NSTREAMS = TS_NSTREAMS
   LIDORT_FixIn%Cont%TS_NLAYERS = TS_NLAYERS
   LIDORT_FixIn%Cont%TS_NFINELAYERS = TS_NFINELAYERS
   LIDORT_FixIn%Cont%TS_N_THERMAL_COEFFS = TS_N_THERMAL_COEFFS
   LIDORT_FixIn%Cont%TS_LIDORT_ACCURACY = TS_LIDORT_ACCURACY
   LIDORT_FixIn%Cont%TS_ASYMTX_TOLERANCE = TS_ASYMTX_TOLERANCE
   LIDORT_FixIn%Cont%TS_TF_MAXITER = TS_TF_MAXITER
   LIDORT_FixIn%Cont%TS_TF_CRITERION = TS_TF_CRITERION
   LIDORT_FixIn%Cont%TS_TOA_ILLUMINATION = TS_TOA_ILLUMINATION
   LIDORT_FixIn%Cont%TS_BOA_ILLUMINATION = TS_BOA_ILLUMINATION

   LIDORT_FixIn%Sunrays%TS_FLUX_FACTOR = TS_FLUX_FACTOR

   LIDORT_FixIn%Chapman%TS_HEIGHT_GRID = TS_HEIGHT_GRID
   LIDORT_FixIn%Chapman%TS_PRESSURE_GRID = TS_PRESSURE_GRID
   LIDORT_FixIn%Chapman%TS_TEMPERATURE_GRID = TS_TEMPERATURE_GRID
   LIDORT_FixIn%Chapman%TS_FINEGRID = TS_FINEGRID
   LIDORT_FixIn%Chapman%TS_RFINDEX_PARAMETER = TS_RFINDEX_PARAMETER

   LIDORT_FixIn%UserVal%TS_N_USER_LEVELS = TS_N_USER_LEVELS

   LIDORT_FixIn%Optical%TS_DELTAU_VERT_INPUT = TS_DELTAU_VERT_INPUT
   LIDORT_FixIn%Optical%TS_PHASMOMS_TOTAL_INPUT = TS_PHASMOMS_TOTAL_INPUT
   LIDORT_FixIn%Optical%TS_PHASFUNC_INPUT_UP = TS_PHASFUNC_INPUT_UP
   LIDORT_FixIn%Optical%TS_PHASFUNC_INPUT_DN = TS_PHASFUNC_INPUT_DN
   LIDORT_FixIn%Optical%TS_LAMBERTIAN_ALBEDO = TS_LAMBERTIAN_ALBEDO
   LIDORT_FixIn%Optical%TS_THERMAL_BB_INPUT = TS_THERMAL_BB_INPUT
   LIDORT_FixIn%Optical%TS_SURFACE_BB_INPUT = TS_SURFACE_BB_INPUT
   LIDORT_FixIn%Optical%TS_ATMOS_WAVELENGTH = TS_ATMOS_WAVELENGTH

   LIDORT_FixIn%Write%TS_DO_DEBUG_WRITE = TS_DO_DEBUG_WRITE
   LIDORT_FixIn%Write%TS_DO_WRITE_INPUT = TS_DO_WRITE_INPUT
   LIDORT_FixIn%Write%TS_INPUT_WRITE_FILENAME = TS_INPUT_WRITE_FILENAME
   LIDORT_FixIn%Write%TS_DO_WRITE_SCENARIO = TS_DO_WRITE_SCENARIO
   LIDORT_FixIn%Write%TS_SCENARIO_WRITE_FILENAME = TS_SCENARIO_WRITE_FILENAME
   LIDORT_FixIn%Write%TS_DO_WRITE_FOURIER = TS_DO_WRITE_FOURIER
   LIDORT_FixIn%Write%TS_FOURIER_WRITE_FILENAME = TS_FOURIER_WRITE_FILENAME
   LIDORT_FixIn%Write%TS_DO_WRITE_RESULTS = TS_DO_WRITE_RESULTS
   LIDORT_FixIn%Write%TS_RESULTS_WRITE_FILENAME = TS_RESULTS_WRITE_FILENAME


   LIDORT_ModIn%MBool%TS_DO_FOCORR = TS_DO_FOCORR
   LIDORT_ModIn%MBool%TS_DO_FOCORR_EXTERNAL = TS_DO_FOCORR_EXTERNAL
   LIDORT_ModIn%MBool%TS_DO_FOCORR_NADIR = TS_DO_FOCORR_NADIR
   LIDORT_ModIn%MBool%TS_DO_FOCORR_OUTGOING = TS_DO_FOCORR_OUTGOING
   LIDORT_ModIn%MBool%TS_DO_SSCORR_TRUNCATION = TS_DO_SSCORR_TRUNCATION
   LIDORT_ModIn%MBool%TS_DO_SSCORR_USEPHASFUNC = TS_DO_SSCORR_USEPHASFUNC
   LIDORT_ModIn%MBool%TS_DO_EXTERNAL_WLEAVE = TS_DO_EXTERNAL_WLEAVE
   LIDORT_ModIn%MBool%TS_DO_DOUBLE_CONVTEST = TS_DO_DOUBLE_CONVTEST
   LIDORT_ModIn%MBool%TS_DO_SOLAR_SOURCES = TS_DO_SOLAR_SOURCES
   LIDORT_ModIn%MBool%TS_DO_REFRACTIVE_GEOMETRY = TS_DO_REFRACTIVE_GEOMETRY
   LIDORT_ModIn%MBool%TS_DO_CHAPMAN_FUNCTION = TS_DO_CHAPMAN_FUNCTION
   LIDORT_ModIn%MBool%TS_DO_RAYLEIGH_ONLY = TS_DO_RAYLEIGH_ONLY
   LIDORT_ModIn%MBool%TS_DO_ISOTROPIC_ONLY = TS_DO_ISOTROPIC_ONLY
   LIDORT_ModIn%MBool%TS_DO_NO_AZIMUTH = TS_DO_NO_AZIMUTH
   LIDORT_ModIn%MBool%TS_DO_ALL_FOURIER = TS_DO_ALL_FOURIER
   LIDORT_ModIn%MBool%TS_DO_DELTAM_SCALING = TS_DO_DELTAM_SCALING
   LIDORT_ModIn%MBool%TS_DO_SOLUTION_SAVING = TS_DO_SOLUTION_SAVING
   LIDORT_ModIn%MBool%TS_DO_BVP_TELESCOPING = TS_DO_BVP_TELESCOPING
   LIDORT_ModIn%MBool%TS_DO_USER_STREAMS = TS_DO_USER_STREAMS
   LIDORT_ModIn%MBool%TS_DO_ADDITIONAL_MVOUT = TS_DO_ADDITIONAL_MVOUT
   LIDORT_ModIn%MBool%TS_DO_MVOUT_ONLY = TS_DO_MVOUT_ONLY
   LIDORT_ModIn%MBool%TS_DO_THERMAL_TRANSONLY = TS_DO_THERMAL_TRANSONLY
   LIDORT_ModIn%MBool%TS_DO_OBSERVATION_GEOMETRY = TS_DO_OBSERVATION_GEOMETRY
   LIDORT_ModIn%MBool%TS_DO_DOUBLET_GEOMETRY = TS_DO_DOUBLET_GEOMETRY

   LIDORT_ModIn%MCont%TS_NMOMENTS_INPUT = TS_NMOMENTS_INPUT

   LIDORT_ModIn%MSunrays%TS_NBEAMS = TS_NBEAMS
   LIDORT_ModIn%MSunrays%TS_BEAM_SZAS = TS_BEAM_SZAS

   LIDORT_ModIn%MUserVal%TS_N_USER_RELAZMS = TS_N_USER_RELAZMS
   LIDORT_ModIn%MUserVal%TS_USER_RELAZMS = TS_USER_RELAZMS
   LIDORT_ModIn%MUserVal%TS_N_USER_STREAMS = TS_N_USER_STREAMS
   LIDORT_ModIn%MUserVal%TS_USER_ANGLES_INPUT = TS_USER_ANGLES_INPUT
   LIDORT_ModIn%MUserVal%TS_USER_LEVELS = TS_USER_LEVELS
   LIDORT_ModIn%MUserVal%TS_GEOMETRY_SPECHEIGHT = TS_GEOMETRY_SPECHEIGHT
   LIDORT_ModIn%MUserVal%TS_N_USER_OBSGEOMS = TS_N_USER_OBSGEOMS
   LIDORT_ModIn%MUserVal%TS_USER_OBSGEOMS_INPUT = TS_USER_OBSGEOMS_INPUT
   LIDORT_ModIn%MUserVal%TS_N_USER_DOUBLETS = TS_N_USER_DOUBLETS
   LIDORT_ModIn%MUserVal%TS_USER_DOUBLETS = TS_USER_DOUBLETS

   LIDORT_ModIn%MChapman%TS_EARTH_RADIUS = TS_EARTH_RADIUS

   LIDORT_ModIn%MOptical%TS_OMEGA_TOTAL_INPUT = TS_OMEGA_TOTAL_INPUT

! Linearization inputs

   LIDORT_LinFixin%Cont%TS_LAYER_VARY_FLAG = TS_LAYER_VARY_FLAG
   LIDORT_LinFixin%Cont%TS_LAYER_VARY_NUMBER = TS_LAYER_VARY_NUMBER
   LIDORT_LinFixin%Cont%TS_N_TOTALCOLUMN_WFS = TS_N_TOTALCOLUMN_WFS
   LIDORT_LinFixIn%Cont%TS_N_SURFACE_WFS = TS_N_SURFACE_WFS
   LIDORT_LinFixin%Cont%TS_N_SLEAVE_WFS = TS_N_SLEAVE_WFS
   LIDORT_LinFixin%Cont%TS_COLUMNWF_NAMES = TS_COLUMNWF_NAMES
   LIDORT_LinFixin%Cont%TS_PROFILEWF_NAMES = TS_PROFILEWF_NAMES

   LIDORT_LinFixIn%Optical%TS_L_DELTAU_VERT_INPUT = TS_L_DELTAU_VERT_INPUT
   LIDORT_LinFixIn%Optical%TS_L_OMEGA_TOTAL_INPUT = TS_L_OMEGA_TOTAL_INPUT
   LIDORT_LinFixIn%Optical%TS_L_PHASMOMS_TOTAL_INPUT = TS_L_PHASMOMS_TOTAL_INPUT
   LIDORT_LinFixIn%Optical%TS_L_PHASFUNC_INPUT_UP = TS_L_PHASFUNC_INPUT_UP
   LIDORT_LinFixIn%Optical%TS_L_PHASFUNC_INPUT_DN = TS_L_PHASFUNC_INPUT_DN


   LIDORT_LinModIn%MCont%TS_DO_COLUMN_LINEARIZATION = TS_DO_COLUMN_LINEARIZATION
   LIDORT_LinModIn%MCont%TS_DO_PROFILE_LINEARIZATION = TS_DO_PROFILE_LINEARIZATION
   LIDORT_LinModIn%MCont%TS_DO_ATMOS_LINEARIZATION = TS_DO_ATMOS_LINEARIZATION
   LIDORT_LinModIn%MCont%TS_DO_SURFACE_LINEARIZATION = TS_DO_SURFACE_LINEARIZATION
   LIDORT_LinModIn%MCont%TS_DO_LINEARIZATION = TS_DO_LINEARIZATION
   LIDORT_LinModIn%MCont%TS_DO_SIMULATION_ONLY = TS_DO_SIMULATION_ONLY
   LIDORT_LinModIn%MCont%TS_DO_ATMOS_LBBF = TS_DO_ATMOS_LBBF
   LIDORT_LinModIn%MCont%TS_DO_SURFACE_LBBF = TS_DO_SURFACE_LBBF
   LIDORT_LinModIn%MCont%TS_DO_SLEAVE_WFS = TS_DO_SLEAVE_WFS


   !  Supplement inputs
   !  -----------------

   LIDORT_Sup%BRDF%TS_EXACTDB_BRDFUNC  = zero
   LIDORT_Sup%BRDF%TS_BRDF_F_0         = zero
   LIDORT_Sup%BRDF%TS_BRDF_F           = zero
   LIDORT_Sup%BRDF%TS_USER_BRDF_F_0    = zero
   LIDORT_Sup%BRDF%TS_USER_BRDF_F      = zero
   LIDORT_Sup%BRDF%TS_EMISSIVITY       = zero
   LIDORT_Sup%BRDF%TS_USER_EMISSIVITY  = zero

   LIDORT_Sup%SLEAVE%TS_SLTERM_ISOTROPIC  = zero
   LIDORT_Sup%SLEAVE%TS_SLTERM_USERANGLES = zero
   LIDORT_Sup%SLEAVE%TS_SLTERM_F_0        = zero
   LIDORT_Sup%SLEAVE%TS_USER_SLTERM_F_0   = zero

!  LIDORT intensity variables

   LIDORT_Sup%SS%TS_INTENSITY_SS  = zero
   LIDORT_Sup%SS%TS_INTENSITY_DB  = zero

!  New for Version 3.8.3.

   LIDORT_Sup%SS%TS_CONTRIBS_SS   = zero

!  LIDORT call
!  -----------

do v = 1, NUM_REPEAT

   CALL LIDORT_LPS_master ( do_debug_input, &
        LIDORT_FixIn,    & ! INPUTS
        LIDORT_ModIn,    & ! INPUTS (possibly modified)
        LIDORT_Sup,      & ! INPUTS/OUTPUTS
        LIDORT_Out,      & ! OUTPUTS
        LIDORT_LinFixIn, & ! INPUTS
        LIDORT_LinModIn, & ! INPUTS (possibly modified)
        LIDORT_LinSup,   & ! INPUTS/OUTPUTS
        LIDORT_LinOut )    ! OUTPUTS
enddo

! Outputs Main
   TS_INTENSITY = LIDORT_Out%Main%TS_INTENSITY
   TS_MEANI_DIFFUSE = LIDORT_Out%Main%TS_MEANI_DIFFUSE
   TS_FLUX_DIFFUSE = LIDORT_Out%Main%TS_FLUX_DIFFUSE
   TS_DNMEANI_DIRECT = LIDORT_Out%Main%TS_DNMEANI_DIRECT
   TS_DNFLUX_DIRECT = LIDORT_Out%Main%TS_DNFLUX_DIRECT
   TS_ALBMED_USER = LIDORT_Out%Main%TS_ALBMED_USER
   TS_TRNMED_USER = LIDORT_Out%Main%TS_TRNMED_USER
   TS_ALBMED_FLUXES = LIDORT_Out%Main%TS_ALBMED_FLUXES
   TS_TRNMED_FLUXES = LIDORT_Out%Main%TS_TRNMED_FLUXES
   TS_PLANETARY_TRANSTERM = LIDORT_Out%Main%TS_PLANETARY_TRANSTERM
   TS_PLANETARY_SBTERM = LIDORT_Out%Main%TS_PLANETARY_SBTERM
   TS_PATHGEOMS = LIDORT_Out%Main%TS_PATHGEOMS
   TS_LOSTRANS = LIDORT_Out%Main%TS_LOSTRANS
   TS_LAYER_MSSTS = LIDORT_Out%Main%TS_LAYER_MSSTS
   TS_SURF_MSSTS = LIDORT_Out%Main%TS_SURF_MSSTS
   TS_CONTRIBS = LIDORT_Out%Main%TS_CONTRIBS

! Outputs Lin Atmos

   TS_COLUMNWF = LIDORT_LinOut%Atmos%TS_COLUMNWF
   TS_MEANI_DIFFUSE_COLWF = LIDORT_LinOut%Atmos%TS_MEANI_DIFFUSE_COLWF
   TS_FLUX_DIFFUSE_COLWF = LIDORT_LinOut%Atmos%TS_FLUX_DIFFUSE_COLWF
   TS_DNMEANI_DIRECT_COLWF = LIDORT_LinOut%Atmos%TS_DNMEANI_DIRECT_COLWF
   TS_DNFLUX_DIRECT_COLWF = LIDORT_LinOut%Atmos%TS_DNFLUX_DIRECT_COLWF
   TS_PROFILEWF = LIDORT_LinOut%Atmos%TS_PROFILEWF
   TS_MEANI_DIFFUSE_PROFWF = LIDORT_LinOut%Atmos%TS_MEANI_DIFFUSE_PROFWF
   TS_FLUX_DIFFUSE_PROFWF = LIDORT_LinOut%Atmos%TS_FLUX_DIFFUSE_PROFWF
   TS_DNMEANI_DIRECT_PROFWF = LIDORT_LinOut%Atmos%TS_DNMEANI_DIRECT_PROFWF
   TS_DNFLUX_DIRECT_PROFWF = LIDORT_LinOut%Atmos%TS_DNFLUX_DIRECT_PROFWF
   TS_ABBWFS_JACOBIANS = LIDORT_LinOut%Atmos%TS_ABBWFS_JACOBIANS
   TS_ABBWFS_FLUXES = LIDORT_LinOut%Atmos%TS_ABBWFS_FLUXES
   TS_ALBMED_USER_PROFWF = LIDORT_LinOut%Atmos%TS_ALBMED_USER_PROFWF
   TS_TRNMED_USER_PROFWF = LIDORT_LinOut%Atmos%TS_TRNMED_USER_PROFWF
   TS_ALBMED_FLUXES_PROFWF = LIDORT_LinOut%Atmos%TS_ALBMED_FLUXES_PROFWF
   TS_TRNMED_FLUXES_PROFWF = LIDORT_LinOut%Atmos%TS_TRNMED_FLUXES_PROFWF
   TS_TRANSBEAM_PROFWF = LIDORT_LinOut%Atmos%TS_TRANSBEAM_PROFWF
   TS_ALBMED_USER_COLWF = LIDORT_LinOut%Atmos%TS_ALBMED_USER_COLWF
   TS_TRNMED_USER_COLWF = LIDORT_LinOut%Atmos%TS_TRNMED_USER_COLWF
   TS_ALBMED_FLUXES_COLWF = LIDORT_LinOut%Atmos%TS_ALBMED_FLUXES_COLWF
   TS_TRNMED_FLUXES_COLWF = LIDORT_LinOut%Atmos%TS_TRNMED_FLUXES_COLWF
   TS_TRANSBEAM_COLWF = LIDORT_LinOut%Atmos%TS_TRANSBEAM_COLWF
   TS_PLANETARY_TRANSTERM_PROFWF = LIDORT_LinOut%Atmos%TS_PLANETARY_TRANSTERM_PROFWF
   TS_PLANETARY_SBTERM_PROFWF = LIDORT_LinOut%Atmos%TS_PLANETARY_SBTERM_PROFWF
   TS_LC_LOSTRANS = LIDORT_LinOut%Atmos%TS_LC_LOSTRANS
   TS_LC_LAYER_MSSTS = LIDORT_LinOut%Atmos%TS_LC_LAYER_MSSTS
   TS_LC_SURF_MSSTS = LIDORT_LinOut%Atmos%TS_LC_SURF_MSSTS
   TS_LP_LOSTRANS = LIDORT_LinOut%Atmos%TS_LP_LOSTRANS
   TS_LP_LAYER_MSSTS = LIDORT_LinOut%Atmos%TS_LP_LAYER_MSSTS
   TS_LP_SURF_MSSTS = LIDORT_LinOut%Atmos%TS_LP_SURF_MSSTS

! Output Lin Surf
   TS_SURFACEWF = LIDORT_LinOut%Surf%TS_SURFACEWF
   TS_MEANI_DIFFUSE_SURFWF = LIDORT_LinOut%Surf%TS_MEANI_DIFFUSE_SURFWF
   TS_FLUX_DIFFUSE_SURFWF = LIDORT_LinOut%Surf%TS_FLUX_DIFFUSE_SURFWF
   TS_SBBWFS_JACOBIANS = LIDORT_LinOut%Surf%TS_SBBWFS_JACOBIANS
   TS_SBBWFS_FLUXES = LIDORT_LinOut%Surf%TS_SBBWFS_FLUXES
   TS_LS_LAYER_MSSTS = LIDORT_LinOut%Surf%TS_LS_LAYER_MSSTS
   TS_LS_SURF_MSSTS = LIDORT_LinOut%Surf%TS_LS_SURF_MSSTS


!   CALL LIDORT_WRITE_STATUS ( &
!        '3p8p3_LIDORT_Execution.log', LIDORT_ERRUNIT, OPENFILEFLAG, LIDORT_Out%Status )
!
!     do v = 1, LIDORT_ModIn%MUserVal%TS_N_USER_OBSGEOMS
!      write(0,*) 'LIDORT intensity = ', LIDORT_Out%Main%TS_intensity(1,v,1)
!      write(0,*) 'LIDORT MS intensity = ', LIDORT_Out%Main%TS_intensity(1,v,1)- &
!                  LIDORT_Sup%SS%TS_INTENSITY_SS(1,v,1)- &
!                  LIDORT_Sup%SS%TS_INTENSITY_DB(1,v)
!      write(0,*) 'LIDORT SS, DB, SS+DB intensity = ', LIDORT_Sup%SS%TS_INTENSITY_SS(1,v,1), &
!                  LIDORT_Sup%SS%TS_INTENSITY_DB(1,v), &
!                  LIDORT_Sup%SS%TS_INTENSITY_SS(1,v,1)+ &
!                  LIDORT_Sup%SS%TS_INTENSITY_DB(1,v)
!   enddo


end
